version: '3.8'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_db
      MYSQL_PASSWORD: devpass
    restart: always
    volumes:
      - db-data:/var/lib/mysql

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db-data: